### ISSUE TITLE
Timebar should be disabled by default

### ISSUE THREAD

**Issue by CodeF53** [MultiCoreNetwork/carpet-redcraft-addons#68]

**Comment by CodeF53** [comment]
every time I open a world, it re-enable's itself, and I personally don't want that.

**Comment by BisUmTo** [comment]
You can disable the timebar rule with command `/carpet commandTimebar false` and set it disabled as default with `/carpet setDefault commandTimebar false`

Otherwise if you want to keep the state beetween rejoins, you can comment out line 39 of the script.

I added the feature that hides automatically the timebar if the rule is disabled in the last commit, so in the new version should be fixed.
